version: "3"
services:
  application:
    image: manjugoal15/devopswithmanju-sb-mysql
    ports:
      - "8080:8080"
    networks:
      - devopswithmanju-network
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    
  mysqldb:
    image: mysql:5.7
    networks:
      - devopswithmanju-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    volumes:
      - /data/mysql
networks:
  devopswithmanju-network:
    external: true
